---
title: "Linear Prediction"
author: "Aditya Khera"
date: "2023-05-07"
output: pdf_document
---

```{r, include=FALSE}
library(tidyverse)
library(caret)
```

## Data Set Up
```{r}
data <- read.csv("/Users/adityakhera/Documents/GitHub/Modeling-Dynamic-Pricing-in-US-Hotels/filtered_data.csv")
model_data <- data[,-c(1,2)]

set.seed(123)
training.samples <- model_data$adr %>%
  createDataPartition(p = 0.8, list = FALSE)
train.data  <- model_data[training.samples, ]
test.data <- model_data[-training.samples, ]
```

## Randomized model
```{r}
set.seed(123)
randctrl <- trainControl(method="cv",
number = 5, search = "random", savePredictions = T)

softlinearfit <- train(adr ~., data = train.data, method = "lm",
               trControl = randctrl)

softlinearfit$bestTune
```
So we should include an intercept in our model, now continue with the normal model.

## Training the model
```{r}
set.seed(123)
train.control <- trainControl(method = "cv", number = 10)
# Train the model
model <- train(adr ~., data = train.data, method = "lm",
               trControl = train.control)
```

## Show some univariate predictions

```{r}
plot(test.data$arrival_date_week_number, test.data$adr, col="red", 
     main = "Average Daily Rate Plotted Against Arrival Date Week",
     xlab = "Arrival Date Week", ylab = "Average Daily Rate")
abline(69.084021, 0.462269)
legend("topright",legend=c("Testing data"),col=c("Red"),pch=c(1,1))
```

```{r}
plot(train.data$children, train.data$adr, main = "Average Daily Rate Plotted Against Children in Reservation",
     xlab = "Children", ylab = "Average Daily Rate")
abline(69.084021, 31.293894)
points(test.data$children, test.data$adr, col="red")
legend("bottomright",legend=c("Testing data","Training data"),col=c("Red","Black"),pch=c(1,1))
```


```{r}
plot(train.data$adults, train.data$adr, main = "Average Daily Rate Plotted Against Adults in Reservation",
     xlab = "Adults", ylab = "Average Daily Rate")
abline(69.084021, 24.208944)
points(test.data$adults, test.data$adr, col="red")
legend("topright",legend=c("Testing data","Training data"),col=c("Red","Black"),pch=c(1,1))
```

```{r}
plot(train.data$total_of_special_requests , train.data$adr, 
     main = "Average Daily Rate Plotted Against Total Special Request",
     xlab = "Total Special Request", ylab = "Average Daily Rate")
abline(69.084021, 6.575232)
points(test.data$total_of_special_requests , test.data$adr, col="red")
legend("topright",legend=c("Testing data","Training data"),col=c("Red","Black"),pch=c(1,1))
```



## Predict on the model, Loss function
```{r}
model$results$RMSE
predictions <- model %>% predict(test.data)
n <- nrow(test.data)
res_squared <- (test.data$adr-predictions)^2
loss <- sqrt(sum(res_squared)/n)
loss
```

